global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'url-check'
    metrics_path: /metrics
    static_configs:
      - targets: ['url-check:4000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
